clc
% Load symbolic constants (instructions)
Instructions
% Addresses
% Video_Adapter
% CharTable

% ROM code definition
RomCode = ...
[
	ADI  r0  1			...
	ADI  r1  1			...
						...
	MRC  r2	 5			...
	SPX  r0  r1  1		...
	ADI  r0  1			...
	ADI  r1  1			...
	JNE	 r0  r2  6		...
						...
	00   00				...
]


% RomCode = reshape(transpose(RomCode), [], 1)
RomCode = Preprocessor(RomCode)

