clc
clear
Test_Arithmetic_Operations();
Test_Bit_Demultiplexers();
Test_Bit_Multiplexers();
Test_Byte_Demultiplexers();
Test_Byte_Multiplexers();
Test_Decoders();
Test_Encoders();
Test_Memory_Blocks();
Test_Word_Multiplexers();
