%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Instruction JLT system test.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
label = ...
{
    'LABEL'
};
for (idx = 1:size(label))
    eval([char(label(idx)),'  = bitor(c.LABEL_SRC_PREFIX,  idx);']);
    eval([char(label(idx)),'_ = bitor(c.LABEL_DEST_PREFIX, idx);']);
end
c.LBL_CNT = idx;



SourceCode = ...
[
                MOVL        r0          h11         ... % r0 = 0x1111
                MOVU        r0          h11         ...
                                                    ...
                MOVL        r1          h55         ... % r1 = 0x5555
                MOVU        r1          h55         ...
                                                    ...
                CMP         r0          r1          ...
                JLT         LABEL                   ...
                                                    ...
                MOVL        r0          hFF         ... % r0 = 0xFFFF
                MOVU        r0          hFF         ...
                                                    ...
    LABEL_      JMP         LABEL                   ... % Expected result: r0 == 0x1111
];

