%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Instruction CMP system test.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
label = ...
{
    'LABEL'
};
for (idx = 1:size(label))
    eval([char(label(idx)),'  = bitor(c.LABEL_SRC_PREFIX,  idx);']);
    eval([char(label(idx)),'_ = bitor(c.LABEL_DEST_PREFIX, idx);']);
end
c.LBL_CNT = idx;



SourceCode = ...
[
                MOVL        r2          0xFF        ... 
                MOVU        r2          0xFF        ...
                                                    ...
                MOVL        r3          0xFF        ...
                MOVU        r3          0xFF        ...
                                                    ...
                CMP         r2          r3          ... % Expected value: r2 == r3
                                                    ...
    LABEL_      JMP         LABEL                   ...
];

