%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Instruction LDLI system test.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
switch section
case 'LABEL'
Label = ...
{
    'LABEL'
};


case 'CODE'
SourceCode = ...
[
                MOVL        r0                      0xAA                    ... % Assign data to store/load.
                MOVU        r0                      0xBB                    ...
                                                                            ...
                SGMT        msb(RAM_START + 5)                              ... % Assign memory address.
                STLI        lsb(RAM_START + 5)      r0                      ...
                                                                            ...
                LDLI        r1                      lsb(RAM_START + 5)      ... % Expected value: r1 == 0x00AA
                                                                            ...
    LABEL_      JMP         LABEL                                           ...
];
end
