%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Instruction LDL system test.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
label = ...
{
    'LABEL'
};
for (idx = 1:size(label))
    eval([char(label(idx)),'  = bitor(c.LABEL_SRC_PREFIX,  idx);']);
    eval([char(label(idx)),'_ = bitor(c.LABEL_DEST_PREFIX, idx);']);
end
c.LBL_CNT = idx;


SourceCode = ...
[
                MOVL        r1          0xAA                    ... % Assign data to store/load.
                MOVU        r1          0xBB                    ...
                                                                ...
                MOVL        r2          0x00                    ... % Clear register.
                MOVU        r2          0x00                    ...
                                                                ...
                MOVL        r3          0xFF                    ... % Set register to some value.
                MOVU        r3          0xFF                    ...
                                                                ...
                MOVL        r0          lsb(c.RAM_START + 0)    ... % Assign memory address.
                MOVU        r0          msb(c.RAM_START + 0)    ...
                STU         m(r0)       r1                      ... % Store register to memory.
                                                                ...
                MOVL        r0          lsb(c.RAM_START + 1)    ... % Assign memory address.
                MOVU        r0          msb(c.RAM_START + 1)    ...
                STL         m(r0)       r1                      ... % Store register to memory.
                                                                ...
                LDL         r2          m(r0)                   ... % Expected value: r2 == 0x00AA
                LDL         r3          m(r0)                   ... % Expected value: r3 == 0xFFAA
                                                                ...
    LABEL_      JMP         LABEL                               ...
];

