label = ...
{
	'LABEL'
};
for (idx = 1:size(label))
	eval([char(label(idx)),'  = bitor(c.LABEL_SRC_PREFIX,  idx);']);
	eval([char(label(idx)),'_ = bitor(c.LABEL_DEST_PREFIX, idx);']);
end
c.LBL_CNT = idx;



SourceCode = ...
[
				MOVL		r0			h00			... % Test 1, expected result: r0 == 0x0000
				MOVU		r0			h00			...
				XOR			r0			r0			...
													...
				MOVL		r1			h11			... % Test 2, expected result: r1 == 0x0000
				MOVU		r1			h11			...
				XOR			r1			r1			...
													...
				MOVL		r2			h00			... % Test 3, expected result: r2 == 0xFFFF
				MOVU		r2			h00			...
				MOVL		r3			hFF			...
				MOVU		r3			hFF			...
				XOR			r2			r3			...
													...
				MOVL		r4			h00			... % Test 4, expected result: r5 == 0xFFFF
				MOVU		r4			h00			...
				MOVL		r5			hFF			...
				MOVU		r5			hFF			...
				XOR			r5			r4			...
													...
	LABEL_		JMP			LABEL					...
];

