label = ...
{
	'LABEL'
};
for (idx = 1:size(label))
	eval([char(label(idx)),'  = bitor(c.LABEL_SRC_PREFIX,  idx);']);
	eval([char(label(idx)),'_ = bitor(c.LABEL_DEST_PREFIX, idx);']);
end
c.LBL_CNT = idx;



SourceCode = ...
[
				MOVL		r0			h00			... % Set memory 0x0000 to value 0x0000.
				MOVU		r0			h00			...
				MOVL		r1			h00			...
				MOVU		r1			h00			...
				STORE		m(r1)		r0			...
													...
				MOVL		r0			hFF			... % Set memory 0x0001 to value 0xFFFF.
				MOVU		r0			hFF			...
				MOVL		r1			h01			...
				MOVU		r1			h01			...
				STORE		m(r1)		r0			...
													...
				MOVL		r0			hAA			... % Assign data to be stored.
				MOVU		r0			hBB			...
				MOVL		r1			h00			...
				MOVU		r1			h00			...
				STOREL		m(r1)		r0			... % Expected value: m(0x0000) == 0x00AA
				MOVL		r1			h01			...
				MOVU		r1			h01			...
				STOREL		m(r1)		r0			... % Expected value: m(0x0001) == 0xFFAA
													...
	LABEL_		JMP			LABEL					...
];
