label = ...
{
	'LABEL'
};
for (idx = 1:size(label))
	eval([char(label(idx)),'  = bitor(c.LABEL_SRC_PREFIX,  idx);']);
	eval([char(label(idx)),'_ = bitor(c.LABEL_DEST_PREFIX, idx);']);
end
c.LBL_CNT = idx;



SourceCode = ...
[
				MOVL		r0			h00			... 
				MOVU		r0			h00			...
													...
				MOVL		r1			h00			...
				MOVU		r1			h00			...
													...
				CMP			r0			r1			... % Expected value: r0 == r1
													...
	LABEL_		JMP			LABEL					...
];

