%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% GP Timer system test.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
switch section
case 'LABEL'
Label = ...
{
    'LABEL'
};


case 'CODE'
SourceCode = ...
[
                SGMT        msb(TIMER_BASE_ADDR)                                            ... % Store Timer base address.
                                                                                            ...
                MOVL        r0                                      0x05                    ... % Configure start value.
                STLI        lsb(CMD_TIMER_SET_START_VALUE)          r0                      ...
                                                                                            ...
                MOVL        r0                                      0xFF                    ... % Configure stop value.
                STLI        lsb(CMD_TIMER_SET_STOP_VALUE)           r0                      ...
                                                                                            ...                
                MOVL        r0                                      TIMER_FREE_RUN          ... % Configure free run mode.
                STLI        lsb(CMD_TIMER_MODE)                     r0                      ...
                                                                                            ...
                MOVL        r0                                      TIMER_RUN               ... % Start timer.
                STLI        lsb(CMD_TIMER_RUN)                      r0                      ...
                                                                                            ...
                ADDI        r0                                      0x00                    ... % Do nothing, wait...
                ADDI        r0                                      0x00                    ... % Do nothing, wait...
                ADDI        r0                                      0x00                    ... % Do nothing, wait...
                ADDI        r0                                      0x00                    ... % Do nothing, wait...
                ADDI        r0                                      0x00                    ... % Do nothing, wait...
                ADDI        r0                                      0x00                    ... % Do nothing, wait...
                ADDI        r0                                      0x00                    ... % Do nothing, wait...
                ADDI        r0                                      0x00                    ... % Do nothing, wait...
                ADDI        r0                                      0x00                    ... % Do nothing, wait...
                ADDI        r0                                      0x00                    ... % Do nothing, wait...
                                                                                            ...
                LDLI        r0                                      lsb(TIMER_BASE_ADDR)    ... % Expected result r0 = 14.
                                                                                            ...
    LABEL_      JMP         LABEL                                                           ...
];
end
