%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Instruction OR system test.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
label = ...
{
    'LABEL'
};
for (idx = 1:size(label))
    eval([char(label(idx)),'  = bitor(c.LABEL_SRC_PREFIX,  idx);']);
    eval([char(label(idx)),'_ = bitor(c.LABEL_DEST_PREFIX, idx);']);
end
c.LBL_CNT = idx;



SourceCode = ...
[
                MOVL        r0          0x00        ... % Test 1, expected result: r0 == 0x0000
                MOVU        r0          0x00        ...
                OR          r0          r0          ...
                                                    ...
                MOVL        r1          0xFF        ... % Test 2, expected result: r1 == 0xFFFF
                MOVU        r1          0xFF        ...
                OR          r1          r1          ...
                                                    ...
                MOVL        r2          0x00        ... % Test 3, expected result: r2 == 0xFFFF
                MOVU        r2          0x00        ...
                MOVL        r3          0xFF        ...
                MOVU        r3          0xFF        ...
                OR          r2          r3          ...
                                                    ...
                MOVL        r4          0x00        ... % Test 4, expected result: r5 == 0xFFFF
                MOVU        r4          0x00        ...
                MOVL        r5          0xFF        ...
                MOVU        r5          0xFF        ...
                OR          r5          r4          ...
                                                    ...
    LABEL_      JMP         LABEL                   ...
];

