label = ...
{
	'LABEL'
};
for (idx = 1:size(label))
	eval([char(label(idx)),'  = bitor(c.LABEL_SRC_PREFIX,  idx);']);
	eval([char(label(idx)),'_ = bitor(c.LABEL_DEST_PREFIX, idx);']);
end
c.LBL_CNT = idx;



SourceCode = ...
[
				MOVL		r0			hAA			... % Load data to store/load.
				MOVU		r0			hBB			...
				MOVL		r1			h05			... % Load memory address.
				MOVU		r1			h00			...
				MOVL		r2			h00			... % Clear register.
				MOVU		r2			h00			...
				STORE		m(r1)		r0			...
				LOADI		r2			m(h05)		... % Expected value: r2 == 0xBBAA
													...
	LABEL_		JMP			LABEL					...
];

