%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Instruction CMP system test.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
switch section
case 'LABEL'
Label = ...
{
    'LABEL'
};


case 'CODE'
SourceCode = ...
[
                MOVL        r2          0xFF        ... 
                MOVU        r2          0xFF        ...
                                                    ...
                MOVL        r3          0xFF        ...
                MOVU        r3          0xFF        ...
                                                    ...
                CMP         r2          r3          ... % Expected value: r2 == r3
                                                    ...
    LABEL_      JMP         LABEL                   ...
];
end
