label = ...
{
	'LABEL'
};
for (idx = 1:size(label))
	eval([char(label(idx)),'  = bitor(c.LABEL_SRC_PREFIX,  idx);']);
	eval([char(label(idx)),'_ = bitor(c.LABEL_DEST_PREFIX, idx);']);
end
c.LBL_CNT = idx;



SourceCode = ...
[
				MOVL		r0			h07			... % r0 = 0xE007
				MOVU		r0			hE0			...
													...
				MOVL		r1			h07			... % r1 = 0xE007
				MOVU		r1			hE0			...
													...
				MOVL		r2			h07			... % r2 = 0xE007
				MOVU		r2			hE0			...
													...
				MOVL		r3			h07			... % r3 = 0xE007
				MOVU		r3			hE0			...
													...
				MOVL		r4			h07			... % r4 = 0xE007
				MOVU		r4			hE0			...
													...
				SHIFTI		r0			  1			... % Expected result: r0 = 0xC00E
				SHIFTI		r1			 15			... % Expected result: r1 = 0x8000
				SHIFTI		r2			 -1			... % Expected result: r2 = 0x7003
				SHIFTI		r3			-15			... % Expected result: r3 = 0x0001
				SHIFTI		r4			  0			... % Expected result: r4 = 0xE007
													...
	LABEL_		JMP			LABEL					...
];

