label = ...
{
	'LABEL'
};
for (idx = 1:size(label))
	eval([char(label(idx)),'  = bitor(c.LABEL_SRC_PREFIX,  idx);']);
	eval([char(label(idx)),'_ = bitor(c.LABEL_DEST_PREFIX, idx);']);
end
c.LBL_CNT = idx;



SourceCode = ...
[
				MOVL		r0			h00			... r0 = 0
				MOVU		r0			h00			...
													...
				MOVL		r1			hFF			... r1 = 32767
				MOVU		r1			h7F			...
													...
				MOVL		r2			hFF			... r2 = -1
				MOVU		r2			hFF			...
													...
				MOVL		r3			h00			... r3 = -32768
				MOVU		r3			h80			...
													...
				MOVL		r4			h01			... r4 = 1
				MOVU		r4			h00			...
													...
				ADD			r0			r2			... % Expected result: r0 = -1
				ADD			r1			r4			... % Expected result: r1 = -32768
				ADD			r3			r2			... % Expected result: r3 =  32767
													...
	LABEL_		JMP			LABEL					...
];

