label = ...
{
	'LABEL'
};
for (idx = 1:size(label))
	eval([char(label(idx)),'  = bitor(c.LABEL_SRC_PREFIX,  idx);']);
	eval([char(label(idx)),'_ = bitor(c.LABEL_DEST_PREFIX, idx);']);
end
c.LBL_CNT = idx;


% This test checks instruction PUSH, POP, CALL and RET.
SourceCode = ...
[
				MOVL		r0			hAA			... % Init registers r0 .. r3 to test values.
				MOVU		r0			hAA			...
													...
				MOVL		r1			hBB			...
				MOVU		r1			hBB			...
													...
				MOVL		r2			hCC			...
				MOVU		r2			hCC			...
													...
				MOVL		r3			hDD			...
				MOVU		r3			hDD			...
													...
													...
				PUSH		r0						... % Stash original values on stack.
				PUSH		r1						...
				PUSH		r2						...
				PUSH		r3						...
													...
													...
				MOVL		r0			h44			... % Set values of registers r0, r1, r2 and r3 to 0x4444.
				MOVU		r0			h44			...
													...
				MOVL		r1			h44			...
				MOVU		r1			h44			...
													...
				MOVL		r2			h44			...
				MOVU		r2			h44			...
													...
				MOVL		r3			h44			...
				MOVU		r3			h44			...
													...
													...
				POP			r3						... % Restore original values from stack.
				POP			r2						...
				POP			r1						...
				POP			r0						...
													...
													...
	LABEL_		JMP			LABEL					... % Expected results: r0 == 0xAAAA, r1 == 0xBBBB, r2 == 0xCCCC, r3 == 0xDDDD
];

