%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Instruction SHIFT system test.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
switch section
case 'LABEL'
Label = ...
{
    'LABEL'
};


case 'CODE'
SourceCode = ...
[
                MOVL        r0          0x07        ... % r0 = 0xE007
                MOVU        r0          0xE0        ...
                                                    ...
                MOVL        r1          0x07        ... % r1 = 0xE007
                MOVU        r1          0xE0        ...
                                                    ...
                MOVL        r2          0x07        ... % r2 = 0xE007
                MOVU        r2          0xE0        ...
                                                    ...
                MOVL        r5          0x01        ... % r5 = 0x0001
                MOVU        r5          0x00        ...
                                                    ...
                MOVL        r6          0x0F        ... % r6 = 0x000F
                MOVU        r6          0x00        ...
                                                    ...
                MOVL        r7          0xFF        ... % r7 = 0xFFFF
                MOVU        r7          0xFF        ...
                                                    ...
                SHIFT       r0          r5          ... % Expected result: r0 = 0xC00E
                SHIFT       r1          r6          ... % Expected result: r1 = 0x8000
                SHIFT       r2          r7          ... % Expected result: r2 = 0x7003
                                                    ...
    LABEL_      JMP         LABEL                   ...
];
end
