%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Instruction LDU system test.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
switch section
case 'LABEL'
Label = ...
{
    'LABEL'
};


case 'CODE'
SourceCode = ...
[
                MOVL        r1          0xAA                    ... % Assign data to store/load.
                MOVU        r1          0xBB                    ...
                                                                ...
                MOVL        r2          0x00                    ... % Clear register.
                MOVU        r2          0x00                    ...
                                                                ...
                MOVL        r3          0xFF                    ... % Set register to some value.
                MOVU        r3          0xFF                    ...
                                                                ...
                MOVL        r0          lsb(RAM_START + 0)      ... % Assign memory address.
                MOVU        r0          msb(RAM_START + 0)      ...
                STU         m(r0)       r1                      ... % Store register to memory.
                                                                ...
                MOVL        r0          lsb(RAM_START + 1)      ... % Assign memory address.
                MOVU        r0          msb(RAM_START + 1)      ...
                STL         m(r0)       r1                      ... % Store register to memory.
                                                                ...
                LDU         r2          m(r0)                   ... % Expected value: r2 == 0xAA00
                LDU         r3          m(r0)                   ... % Expected value: r3 == 0xAAFF
                                                                ...
    LABEL_      JMP         LABEL                               ...
];
end
