%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Instruction MOVU system test.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
label = ...
{
    'LABEL'
};
for (idx = 1:size(label))
    eval([char(label(idx)),'  = bitor(c.LABEL_SRC_PREFIX,  idx);']);
    eval([char(label(idx)),'_ = bitor(c.LABEL_DEST_PREFIX, idx);']);
end
c.LBL_CNT = idx;


SourceCode = ...
[
                MOVL        r0          h00         ... 
                MOVU        r0          h00         ...
                MOVU        r0          hBB         ... % Expected value: r0 == 0xBB00
                                                    ...
                MOVL        r1          hFF         ...
                MOVU        r1          hFF         ...
                MOVU        r1          hBB         ... % Expected value: r1 == 0xBBFF
                                                    ...
    LABEL_      JMP         LABEL                   ...
];

