%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Instruction MOVL system test.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
label = ...
{
    'LABEL'
};
for (idx = 1:size(label))
    eval([char(label(idx)),'  = bitor(c.LABEL_SRC_PREFIX,  idx);']);
    eval([char(label(idx)),'_ = bitor(c.LABEL_DEST_PREFIX, idx);']);
end
c.LBL_CNT = idx;


SourceCode = ...
[
                MOVL        r0          h00         ... 
                MOVU        r0          h00         ...
                MOVL        r0          hAA         ... % Expected value: r0 == 0xFFAA
                                                    ...
                MOVL        r1          h00         ... 
                MOVU        r1          h00         ...
                MOVL        r1          h55         ... % Expected value: r1 == 0x0055
                                                    ...
    LABEL_      JMP         LABEL                   ...
];

