%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Instruction JLT system test.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
switch section
case 'LABEL'
Label = ...
{
    'LABEL'
};


case 'CODE'
SourceCode = ...
[
                MOVL        r0          0x11        ... % r0 = 0x1111
                MOVU        r0          0x11        ...
                                                    ...
                MOVL        r1          0x55        ... % r1 = 0x5555
                MOVU        r1          0x55        ...
                                                    ...
                CMP         r0          r1          ...
                JLT         LABEL                   ...
                                                    ...
                MOVL        r0          0xFF        ... % r0 = 0xFFFF
                MOVU        r0          0xFF        ...
                                                    ...
    LABEL_      JMP         LABEL                   ... % Expected result: r0 == 0x1111
];
end
