label = ...
{
	'LABEL'
};
for (idx = 1:size(label))
	eval([char(label(idx)),'  = bitor(c.LABEL_SRC_PREFIX,  idx);']);
	eval([char(label(idx)),'_ = bitor(c.LABEL_DEST_PREFIX, idx);']);
end
c.LBL_CNT = idx;



SourceCode = ...
[
				MOVL		r0			h07			... % r0 = 0xE007
				MOVU		r0			hE0			...
													...
				MOVL		r1			h07			... % r1 = 0xE007
				MOVU		r1			hE0			...
													...
				MOVL		r2			h07			... % r2 = 0xE007
				MOVU		r2			hE0			...
													...
				MOVL		r3			h07			... % r3 = 0xE007
				MOVU		r3			hE0			...
													...
				MOVL		r4			h07			... % r4 = 0xE007
				MOVU		r4			hE0			...
													...
				MOVL		r5			h01			... % r5 = 0x0001
				MOVU		r5			h00			...
													...
				MOVL		r6			h0F			... % r6 = 0x000F
				MOVU		r6			h00			...
													...
				MOVL		r7			hFF			... % r7 = 0xFFFF
				MOVU		r7			hFF			...
													...
				MOVL		r8			hF1			... % r8 = 0xFFF1
				MOVU		r8			hFF			...
													...
				MOVL		r9			h00			... % r9 = 0x0000
				MOVU		r9			h00			...
													...
				SHIFT		r0			r5			... % Expected result: r0 = 0xC00E
				SHIFT		r1			r6			... % Expected result: r1 = 0x8000
				SHIFT		r2			r7			... % Expected result: r2 = 0x7003
				SHIFT		r3			r8			... % Expected result: r3 = 0x0001
				SHIFT		r4			r9			... % Expected result: r4 = 0xE007
													...
	LABEL_		JMP			LABEL					...
];

