%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%  Keyboard interrupt system test
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
switch section
case 'LABEL'
Label = ...
{
    'LABEL'
};


case 'CODE'
SourceCode = ...
[
                MOVL        r7                                      0b00000100              ... Enable timer interrupt.
                SGMT        msb(IRQ_ENBL_REG)                                               ...
                STLI        lsb(IRQ_ENBL_REG)                       r7                      ...
                                                                                            ...
                SGMT        msb(TIMER_BASE_ADDR)                                            ... % Configure and start timer.
                MOVL        r0                                      0x00                    ... % Configure start value.
                STLI        lsb(CMD_TIMER_SET_START_VALUE)          r0                      ...
                MOVL        r0                                      0x0F                    ... % Configure stop value.
                STLI        lsb(CMD_TIMER_SET_STOP_VALUE)           r0                      ...
                MOVL        r0                                      TIMER_FREE_RUN          ... % Configure free run mode.
                STLI        lsb(CMD_TIMER_MODE)                     r0                      ...
                MOVL        r0                                      TIMER_RUN               ... % Start timer.
                STLI        lsb(CMD_TIMER_RUN)                      r0                      ...
                                                                                            ...
                MOVL        r1                                      0xFF                    ... Set r1 to some value just to show that this code was executed.
                MOVU        r1                                      0xFF                    ...
                                                                                            ...
    LABEL_      JMP         LABEL                                                           ... Expected value: r5 = 5 (r5 should be set by the timer IRQ handler placed on address IRQ_ADDR_TIMER).
];
end
