%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Instruction CMP system test.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
switch section
case 'LABEL'
Label = ...
{
    'LABEL'
};


case 'CODE'
SourceCode = ...
[
                MOVL        r0          0x00        ... 
                MOVU        r0          0x00        ...
                                                    ...
                MOVL        r1          0x00        ...
                MOVU        r1          0x00        ...
                                                    ...
                CMP         r0          r1          ... % Expected value: r0 == r1
                                                    ...
    LABEL_      JMP         LABEL                   ...
];
end
