%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Instruction MOVL system test.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
switch section
case 'LABEL'
Label = ...
{
    'LABEL'
};


case 'CODE'
SourceCode = ...
[
                MOVL        r0          0x00        ... 
                MOVU        r0          0x00        ...
                MOVL        r0          0xAA        ... % Expected value: r0 == 0xFFAA
                                                    ...
                MOVL        r1          0x00        ... 
                MOVU        r1          0x00        ...
                MOVL        r1          0x55        ... % Expected value: r1 == 0x0055
                                                    ...
    LABEL_      JMP         LABEL                   ...
];
end
