%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Instruction STU system test.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
switch section
case 'LABEL'
Label = ...
{
    'LABEL'
};


case 'CODE'
SourceCode = ...
[
                MOVL        r0          0x11                    ... % Init test data.
                MOVU        r0          0x22                    ...
                MOVL        r1          0x33                    ...
                MOVU        r1          0x44                    ...
                MOVL        r2          0x55                    ...
                MOVU        r2          0x66                    ...
                MOVL        r3          0x77                    ...
                MOVU        r3          0x88                    ...
                                                                ...
                MOVL        r4          lsb(RAM_START + 0)      ... % Set memory to value 0x22.
                MOVU        r4          msb(RAM_START + 0)      ...
                STU         m(r4)       r0                      ...
                                                                ...
                MOVL        r4          lsb(RAM_START + 255)    ... % Set memory to value 0x44.
                MOVU        r4          msb(RAM_START + 255)    ...
                STU         m(r4)       r1                      ...
                                                                ...
                MOVL        r4          lsb(RAM_START + 256)    ... % Set memory to value 0x66.
                MOVU        r4          msb(RAM_START + 256)    ...
                STU         m(r4)       r2                      ...
                                                                ...
                MOVL        r4          lsb(RAM_START + 511)    ... % Set memory to value 0x88.
                MOVU        r4          msb(RAM_START + 511)    ...
                STU         m(r4)       r3                      ...
                                                                ...
    LABEL_      JMP         LABEL                               ...
];
end
