%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Instruction SHIFTI system test.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
switch section
case 'LABEL'
Label = ...
{
    'LABEL'
};


case 'CODE'
SourceCode = ...
[
                MOVL        r0          0x07        ... % r0 = 0xE007
                MOVU        r0          0xE0        ...
                                                    ...
                MOVL        r1          0x07        ... % r1 = 0xE007
                MOVU        r1          0xE0        ...
                                                    ...
                MOVL        r2          0x07        ... % r2 = 0xE007
                MOVU        r2          0xE0        ...
                                                    ...
                MOVL        r3          0x07        ... % r3 = 0xE007
                MOVU        r3          0xE0        ...
                                                    ...
                MOVL        r4          0x07        ... % r4 = 0xE007
                MOVU        r4          0xE0        ...
                                                    ...
                SHIFTI      r0            1         ... % Expected result: r0 = 0xC00E
                SHIFTI      r1           15         ... % Expected result: r1 = 0x8000
                SHIFTI      r2           -1         ... % Expected result: r2 = 0x7003
                SHIFTI      r3          -15         ... % Expected result: r3 = 0x0001
                SHIFTI      r4            0         ... % Expected result: r4 = 0xE007
                                                    ...
    LABEL_      JMP         LABEL                   ...
];
end
