%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Instruction MOVU system test.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
label = ...
{
    'LABEL'
};
for (idx = 1:size(label))
    eval([char(label(idx)),'  = bitor(c.LABEL_SRC_PREFIX,  idx);']);
    eval([char(label(idx)),'_ = bitor(c.LABEL_DEST_PREFIX, idx);']);
end
c.LBL_CNT = idx;


SourceCode = ...
[
                MOVL        r0          0x00        ... 
                MOVU        r0          0x00        ...
                MOVU        r0          0xBB        ... % Expected value: r0 == 0xBB00
                                                    ...
                MOVL        r1          0xFF        ...
                MOVU        r1          0xFF        ...
                MOVU        r1          0xBB        ... % Expected value: r1 == 0xBBFF
                                                    ...
    LABEL_      JMP         LABEL                   ...
];

