%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%  Keyboard interrupt system test
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
switch section
case 'LABEL'
Label = ...
{
    'LABEL'
};


case 'CODE'
SourceCode = ...
[
                MOVL        r7                                      0b00001100              ... Enable keyboard and timer interrupts.
                SGMT        msb(c.IRQ_ENBL_REG)                                             ...
                STLI        lsb(c.IRQ_ENBL_REG)                     r7                      ...
                                                                                            ...
                SGMT        msb(c.TIMER_BASE_ADDR)                                          ... % Configure and start timer.
                MOVL        r0                                      0x00                    ... % Configure start value.
                STLI        lsb(c.CMD_TIMER_SET_START_VALUE)        r0                      ...
                MOVL        r0                                      0x0F                    ... % Configure stop value.
                STLI        lsb(c.CMD_TIMER_SET_STOP_VALUE)         r0                      ...
                MOVL        r0                                      c.TIMER_FREE_RUN        ... % Configure free run mode.
                STLI        lsb(c.CMD_TIMER_MODE)                   r0                      ...
                MOVL        r0                                      c.TIMER_RUN             ... % Start timer.
                STLI        lsb(c.CMD_TIMER_RUN)                    r0                      ...
                                                                                            ...
    LABEL_      JMP         LABEL                                                           ... Expected value: r5 = 5, r6 = 3 (r5 and r6 should be set by the IRQ handlers placed on addresses IRQ_ADDR_KEYBOARD and IRQ_ADDR_TIMER).
];
end
