%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Instruction NOT system test.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
label = ...
{
    'LABEL'
};
for (idx = 1:size(label))
    eval([char(label(idx)),'  = bitor(c.LABEL_SRC_PREFIX,  idx);']);
    eval([char(label(idx)),'_ = bitor(c.LABEL_DEST_PREFIX, idx);']);
end
c.LBL_CNT = idx;



SourceCode = ...
[
                MOVL        r0          h00         ... % Test 1, expected result: r0 == 0xFFFF
                MOVU        r0          h00         ...
                NOT         r0                      ...
                                                    ...
                MOVL        r1          h55         ... % Test 2, expected result: r0 == 0xAAAA
                MOVU        r1          h55         ...
                NOT         r1                      ...
                                                    ...
                MOVL        r2          hFF         ... % Test 3, expected result: r0 == 0x0000
                MOVU        r2          hFF         ...
                NOT         r2                      ...
                                                    ...
    LABEL_      JMP         LABEL                   ...
];

