%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Instruction ADD system test.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
label = ...
{
    'LABEL'
};
for (idx = 1:size(label))
    eval([char(label(idx)),'  = bitor(c.LABEL_SRC_PREFIX,  idx);']);
    eval([char(label(idx)),'_ = bitor(c.LABEL_DEST_PREFIX, idx);']);
end
c.LBL_CNT = idx;



SourceCode = ...
[
                MOVL        r0          0x00        ... r0 = 0
                MOVU        r0          0x00        ...
                                                    ...
                MOVL        r1          0xFF        ... r1 = 32767
                MOVU        r1          0x7F        ...
                                                    ...
                MOVL        r2          0xFF        ... r2 = -1
                MOVU        r2          0xFF        ...
                                                    ...
                MOVL        r3          0x00        ... r3 = -32768
                MOVU        r3          0x80        ...
                                                    ...
                MOVL        r4          0x01        ... r4 = 1
                MOVU        r4          0x00        ...
                                                    ...
                ADD         r0          r2          ... % Expected result: r0 = -1
                ADD         r1          r4          ... % Expected result: r1 = -32768
                ADD         r3          r2          ... % Expected result: r3 =  32767
                                                    ...
    LABEL_      JMP         LABEL                   ...
];

