%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%  Keyboard interrupt system test
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
label = ...
{
    'LABEL'
};
for (idx = 1:size(label))
    eval([char(label(idx)),'  = bitor(c.LABEL_SRC_PREFIX,  idx);']);
    eval([char(label(idx)),'_ = bitor(c.LABEL_DEST_PREFIX, idx);']);
end
c.LBL_CNT = idx;


SourceCode = ...
[
                MOVL        r7                                      0b00000100              ... Enable timer interrupt.
                SGMT        msb(c.IRQ_ENBL_REG)                                             ...
                STLI        lsb(c.IRQ_ENBL_REG)                     r7                      ...
                                                                                            ...
                SGMT        msb(c.TIMER_BASE_ADDR)                                          ... % Configure and start timer.
                MOVL        r0                                      0x00                    ... % Configure start value.
                STLI        lsb(c.CMD_TIMER_SET_START_VALUE)        r0                      ...
                MOVL        r0                                      0x0F                    ... % Configure stop value.
                STLI        lsb(c.CMD_TIMER_SET_STOP_VALUE)         r0                      ...
                MOVL        r0                                      c.TIMER_FREE_RUN        ... % Configure free run mode.
                STLI        lsb(c.CMD_TIMER_MODE)                   r0                      ...
                MOVL        r0                                      c.TIMER_RUN             ... % Start timer.
                STLI        lsb(c.CMD_TIMER_RUN)                    r0                      ...
                                                                                            ...
                MOVL        r1                                      0xFF                    ... Set r1 to some value just to show that this code was executed.
                MOVU        r1                                      0xFF                    ...
                                                                                            ...
    LABEL_      JMP         LABEL                                                           ... Expected value: r5 = 5 (r5 should be set by the timer IRQ handler placed on address IRQ_ADDR_TIMER).
];
