%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Instruction LDUI system test.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
switch section
case 'LABEL'
Label = ...
{
    'LABEL'
};


case 'CODE'
SourceCode = ...
[
                MOVL        r0                      0xAA                    ... % Assign data to store/load.
                MOVU        r0                      0xBB                    ...
                                                                            ...
                SGMT        msb(c.RAM_START + 5)                            ... % Assign memory address.
                STLI        lsb(c.RAM_START + 5)    r0                      ...
                                                                            ...
                LDUI        r1                      lsb(c.RAM_START + 5)    ... % Expected value: r1 == 0xAA00
                                                                            ...
    LABEL_      JMP         LABEL                                           ...
];
end
