%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Instruction ADDI system test.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
label = ...
{
    'LABEL'
};
for (idx = 1:size(label))
    eval([char(label(idx)),'  = bitor(c.LABEL_SRC_PREFIX,  idx);']);
    eval([char(label(idx)),'_ = bitor(c.LABEL_DEST_PREFIX, idx);']);
end
c.LBL_CNT = idx;



SourceCode = ...
[
                MOVL        r0          0x00        ... r0 = 0
                MOVU        r0          0x00        ...
                                                    ...
                MOVL        r1          0xFF        ... r1 = 32767
                MOVU        r1          0x7F        ...
                                                    ...
                MOVL        r3          0x00        ... r3 = -32768
                MOVU        r3          0x80        ...
                                                    ...
                ADDI        r0          -1          ... % Expected result: r0 = -1
                ADDI        r1           1          ... % Expected result: r1 = -32768
                ADDI        r3          -1          ... % Expected result: r3 =  32767
                                                    ...
    LABEL_      JMP         LABEL                   ...
];

