label = ...
{
	'LABEL'
};
for (idx = 1:size(label))
	eval([char(label(idx)),'  = bitor(c.LABEL_SRC_PREFIX,  idx);']);
	eval([char(label(idx)),'_ = bitor(c.LABEL_DEST_PREFIX, idx);']);
end
c.LBL_CNT = idx;



SourceCode = ...
[
				MOVL		r0			h00			...
				MOVU		r0			h00			...
				NOT			r0						...
													...
				MOVL		r1			h55			...
				MOVU		r1			h55			...
				NOT			r1						...
													...
				MOVL		r2			hFF			...
				MOVU		r2			hFF			...
				NOT			r2						...
													...
	LABEL_		JMP			LABEL					...
];

